image: node:16

stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - deployer # The runner tag for this job
  script:
    - cd react_app # Navigate to the react_app folder
    - npm ci # Install dependencies
    - npm run build # Build the React app
    - mv build ../public # Move the build folder to the root's public folder
  artifacts:
    paths:
      - public
  only:
    - main # or master, depending on your default branch
